const operators = {
  '&': 'AND',
  '|': 'PIPE',
  '|&': 'PIPE_AND',
  '((': 'DOUBLE_OPEN_PAREN',
  '))': 'DOUBLE_CLOSE_PAREN',
  '(': 'OPEN_PAREN',
  ')': 'CLOSE_PAREN',
  '>': 'GREAT',
  '<': 'LESS',
  '&&': 'AND_IF',
  '||': 'OR_IF',
  ';;': 'DSEMI',
  ';&': 'SEMI_AND',
  ';;&': 'DSEMI_AND',
  '<<': 'DLESS',
  '<<<': 'TLESS',
  '>>': 'DGREAT',
  '<&': 'LESSAND',
  '>&': 'GREATAND',
  '<>': 'LESSGREAT',
  '<<-': 'DLESSDASH',
  '>|': 'CLOBBER',
  // bash's own: stdout and stderr both to the file, `cmd &> log`, `cmd &>> log`
  '&>': 'AND_GREAT',
  '&>>': 'AND_DGREAT',
  ';': 'SEMICOLON',
};

export default operators;
